---
- name: Creating CheckMK folders
  hosts: all
  vars_files:
    - /home/ansible/variables/vars_file.yml
    - ../../sites/{{ customer_name }}/CM/{{ site }}/playbooks/CMK/site_vars.yml
  tasks:
    - name: Validating required vault variables
      ansible.builtin.include_tasks: ../../commons/validate-vault-keys.yml
      vars:
        required_vars:
          - cmk_secret
    - name: Creating a CheckMK folder
      checkmk.general.folder:
        server_url: "{{ cmk_url }}"
        site: "{{ cmk_site }}"
        automation_user: "{{ cmk_user }}"
        automation_secret: "{{ cmk_secret }}"
        path: "/{{ item }}"
        name: "{{ item }}"
        state: "present"
      loop: "{{ cmk_folders }}"
