---
- name: Adding host to folder
  hosts: all
  vars_files:
    - /home/ansible/variables/vars_file.yml
    - ../../sites/{{ customer_name }}/CM/{{ site }}/playbooks/CMK/site_vars.yml
  tasks:
    - name: Validating required vault variables
      ansible.builtin.include_tasks: ../../commons/validate-vault-keys.yml
      vars:
        required_vars:
          - cmk_secret
    - name: Adding host into corresponding folder
      checkmk.general.host:
        server_url: "{{ cmk_url }}"
        site: "{{ cmk_site }}"
        automation_user: "{{ cmk_user }}"
        automation_secret: "{{ cmk_secret }}"
        name: "{{ item.key }}"
        attributes:
          ipaddress: "{{ item.value.ip }}"
        folder: "{{ item.value.folder }}"
        state: "present"
      loop: "{{ cmk_monitored_hosts | dict2items }}"
