---
- name: Installing CheckMK Agent on Linux hosts
  hosts: all
  vars_files:
    - /home/ansible/variables/vars_file.yml
    - ../../sites/{{ customer_name }}/CM/{{ site }}/playbooks/CMK/site_vars.yml
  tasks:
    - name: Validating required vault variables
      ansible.builtin.include_tasks: ../../commons/validate-vault-keys.yml
      vars:
        required_vars:
          - registration_user_secret
    - name: Importing GPG key for CheckMK
      ansible.builtin.rpm_key:
        state: present
        key: "{{ cmk_public_key }}"
        validate_certs: "{{ cmk_agent_validate_certs | default(false) }}"
      loop: "{{ cmk_monitored_hosts | dict2items }}"
      delegate_to: "{{ item.value.ip }}"
      when: item.value.folder in cmk_agent_linux_host_folders
    - name: Installing CheckMK agent for Linux hosts
      ansible.builtin.dnf:
        name: "{{ cmk_rpm_agent_package_url }}"
        state: present
        validate_certs: "{{ cmk_agent_validate_certs | default(false) }}"
      loop: "{{ cmk_monitored_hosts | dict2items }}"
      delegate_to: "{{ item.value.ip }}"
      when: item.value.folder in cmk_agent_linux_host_folders
    - name: Registering CheckMK agent using resolved hostname
      ansible.builtin.shell: |
        cmk-agent-ctl register \
        --hostname {{ item.key }} \
        --server {{ cmk_url | urlsplit('hostname') }} \
        --site {{ cmk_site }} \
        --user registration \
        --password {{ registration_user_secret }} \
        --trust-cert
      register: register_output
      loop: "{{ cmk_monitored_hosts | dict2items }}"
      delegate_to: "{{ item.value.ip }}"
      changed_when: register_output.rc == 0
      when: item.value.folder in cmk_agent_linux_host_folders
    - name: Allowing firewalld port for CheckMK Agent
      ansible.posix.firewalld:
        port: "{{ cmk_agent_firewall_port }}/tcp"
        state: enabled
        immediate: true
        permanent: true
      loop: "{{ cmk_monitored_hosts | dict2items }}"
      delegate_to: "{{ item.value.ip }}"
      when: item.value.folder in cmk_agent_linux_host_folders
