---
- name: Running CheckMK service discovery on newly added hosts
  hosts: all
  vars_files:
    - /home/ansible/variables/vars_file.yml
    - ../../sites/{{ customer_name }}/CM/{{ site }}/playbooks/CMK/site_vars.yml
  tasks:
    - name: Validating required vault variables
      ansible.builtin.include_tasks: ../../commons/validate-vault-keys.yml
      vars:
        required_vars:
          - cmk_secret
    - name: Discovering services on hosts
      checkmk.general.discovery:
        server_url: "{{ cmk_url }}"
        site: "{{ cmk_site }}"
        automation_user: "{{ cmk_user }}"
        automation_secret: "{{ cmk_secret }}"
        hosts:
          - "{{ item.key }}"
        state: "fix_all"
      loop: "{{ cmk_monitored_hosts | dict2items }}"
