---
- name: Running CheckMK Site Activation
  hosts: all
  vars_files:
    - /home/ansible/variables/vars_file.yml
    - ../../envs/{{ customer_name }}/CM/{{ site }}/playbooks/CMK/site_vars.yml
  tasks:
    - name: Running CheckMK Site activation."
      checkmk.general.activation:
        server_url: "{{ cmk_url }}"
        site: "{{ cmk_site }}"
        automation_user: "{{ cmk_user }}"
        automation_secret: "{{ cmk_secret }}"
        force_foreign_changes: 'true'
        sites:
          - "{{ cmk_site }}"
