---
- name: Update root Password
  hosts: all
  vars_files:
    # new_root_password is defined in the vault file
    - /home/ansible/variables/vars_file.yml
  tasks:
    - name: Generating SHA-512 hash for new root password
      ansible.builtin.shell: |
        openssl passwd -6 {{ new_root_password | quote }}
      register: root_pass_hash
    - name: Setting root password
      ansible.builtin.user:
        name: root
        password: "{{ root_pass_hash.stdout }}"