## ______________________________
## Server:
## ______________________________
# - ansible.builtin.import_playbook: ../../../../../services/checkmk/checkmk-install.yml
# - ansible.builtin.import_playbook: ../../../../../services/checkmk/1-checkmk-folder-creation.yml
# - ansible.builtin.import_playbook: ../../../../../services/checkmk/2-checkmk-add-host-to-folder.yml
# - ansible.builtin.import_playbook: ../../../../../services/grafana/grafana-server-install.yml
# - ansible.builtin.import_playbook: ../../../../../services/grafana/grafana-api-creation.yml
# - ansible.builtin.import_playbook: ../../../../../services/grafana/grafana-connection-creation.yml
# - ansible.builtin.import_playbook: ../../../../../services/grafana/grafana-datasource-uid-get.yml

## ______________________________
## All:
## ______________________________
# - ansible.builtin.import_playbook: ../../../../../services/checkmk/3.1-checkmk-agent-install-linux.yml

## ______________________________
## Server:
## ______________________________
# - ansible.builtin.import_playbook: ../../../../../services/checkmk/4-checkmk-service-discovery.yml
# - ansible.builtin.import_playbook: ../../../../../services/checkmk/5-checkmk-site-activation.yml
